/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/loop': RouteRecordInfo<'/albums/loop', '/albums/loop', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/说明文档': RouteRecordInfo<'/posts/说明文档', '/posts/说明文档', Record<never, never>, Record<never, never>>,
    '/posts/article_1': RouteRecordInfo<'/posts/article_1', '/posts/article_1', Record<never, never>, Record<never, never>>,
    '/posts/article_10': RouteRecordInfo<'/posts/article_10', '/posts/article_10', Record<never, never>, Record<never, never>>,
    '/posts/article_11': RouteRecordInfo<'/posts/article_11', '/posts/article_11', Record<never, never>, Record<never, never>>,
    '/posts/article_12': RouteRecordInfo<'/posts/article_12', '/posts/article_12', Record<never, never>, Record<never, never>>,
    '/posts/article_13': RouteRecordInfo<'/posts/article_13', '/posts/article_13', Record<never, never>, Record<never, never>>,
    '/posts/article_14': RouteRecordInfo<'/posts/article_14', '/posts/article_14', Record<never, never>, Record<never, never>>,
    '/posts/article_15': RouteRecordInfo<'/posts/article_15', '/posts/article_15', Record<never, never>, Record<never, never>>,
    '/posts/article_2': RouteRecordInfo<'/posts/article_2', '/posts/article_2', Record<never, never>, Record<never, never>>,
    '/posts/article_3': RouteRecordInfo<'/posts/article_3', '/posts/article_3', Record<never, never>, Record<never, never>>,
    '/posts/article_4': RouteRecordInfo<'/posts/article_4', '/posts/article_4', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
